elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
    - ./elasticsearch/config:/etc/elasticsearch/
    - ./elasticsearch/storage:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  build: logstash/
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/patterns:/opt/logstash/patterns
  ports:
    - "5000:5000"
    - "81:80"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
